#!/bin/bash

############################################################################
# Copyright 2015 IoT.bzh
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################

# Author: Stephane Desneux
# Date:   October-2015
# Object: Enter inside a container (shortcut to docker-exec with proper args)
# Version: @VERSION@
# Revision: @URL@ @REVISION@

[[ -z "$1" ]] && { echo "Usage: $0 <containerID>"; exit 1; }

if ! docker ps | tail -n +2 | grep $1 >/dev/null; then
	echo "Error: Invalid container ID" >&2
	echo >&2
	docker ps
	exit 1
fi

docker exec -it $1 /bin/bash
